POSTGRESQL:
  - name: health-check
    sql: SELECT VERSION()
  - name: Person
    sql: SELECT * FROM person ORDER BY id LIMIT $limit OFFSET $offset
  - name: Person_with_id
    sql: |
      SELECT 
      p.*,
      STRING_AGG(DISTINCT cle.identifier, ',') AS courseLearningExperienceIds,
      STRING_AGG(DISTINCT c.courseId::text, ',') AS courseIds,
      STRING_AGG(DISTINCT ple.identifier, ',') AS programLearningExperienceIds,
      STRING_AGG(DISTINCT pr.programId, ',') AS programIds,
      STRING_AGG(DISTINCT ca.id, ',') AS credentialAwardIds,
      STRING_AGG(DISTINCT cr.id, ',') AS credentialIds,
      STRING_AGG(DISTINCT cm.id, ',') AS competencyIds
      FROM 
      person p
      LEFT JOIN 
      courseLearningExperience cle ON p.id = cle.personId
      LEFT JOIN 
      courseAndLearningExperienceAssociation cla ON cla.courseLearningExperienceId = cle.identifier
      LEFT JOIN course c ON c.courseId = cla.courseId  
      LEFT JOIN 
      programLearningExperience ple ON p.id = ple.personId
      LEFT JOIN 
      program pr ON pr.programLearningExperienceId = ple.identifier
      LEFT JOIN 
      credentialAward ca ON p.id = ca.credentialAwardee
      LEFT JOIN 
      credential cr ON cr.credentialAwardId = ca.id
      LEFT JOIN 
      competency cm ON p.id = cm.personId
      where p.id = %s
      GROUP BY 
      p.id, p.firstName, p.lastName, p.birthDate, p.email
  - name: Person_for_Course_name
    sql: SELECT p.id,p.firstName, p.lastName,p.email,c.name as course_name,c.description as course_description FROM course c JOIN courseAndLearningExperienceAssociation clea ON c.courseId = clea.courseId JOIN courseLearningExperience cl on clea.courseLearningExperienceId = cl.identifier JOIN person p ON p.id = cl.personId WHERE c.name = %s
  - name: Person_for_Competency_name
    sql: SELECT p.id, p.firstName, p.lastName, p.birthDate, p.email FROM person p JOIN competency c ON p.id = c.personId WHERE c.name = %s
  - name: Person_for_Course_Competency_name
    sql: SELECT p.id,p.firstName, p.lastName,p.email,c.name as course_name,
      c.description as course_description , cm.name as competency_name, cm.code as competency_code
      FROM person p JOIN courseLearningExperience cl  ON p.id = cl.personId JOIN courseAndLearningExperienceAssociation clea ON clea.courseLearningExperienceId = cl.identifier JOIN course c ON c.courseId = clea.courseId
      JOIN competency cm ON p.id = cm.personId
      WHERE c.name = %s and cm.name = %s
    parameter_order: course_name, competency_name
  - name: Person_for_Credential_Achievement_Type
    sql: |
      SELECT  
      	id ,
      person_name->>'firstName' AS first_name,
      person_name->>'lastName' AS last_name,
      person_name->>'email' AS email,
      credential->'Credential'->>'id' AS credential_id,
      credential->'Credential'->>'name' AS credential_name,
      credential->'Credential'->'Image'->>'imageId' AS credential_image,
      credential->'Credential'->>'description' AS credential_description,
      credential->'Credential'->>'format' AS credential_format 
      FROM 
          lif_record,
          jsonb_array_elements(record::jsonb->'Person') AS person,
          jsonb_array_elements(person->'Name') AS person_name,
          jsonb_array_elements(person->'CredentialAward') AS credential
      WHERE 
          credential->'Credential'->>'achievementType' = %s
  ###################################### 
  - name: Course
    sql: SELECT * FROM public.course ORDER BY courseId LIMIT $limit OFFSET $offset
  - name: Course_with_id
    sql: SELECT * FROM public.course WHERE courseId = %s
  ######################################
  - name: Credential
    sql: SELECT * FROM credential ORDER BY id LIMIT $limit OFFSET $offset
  - name: Credential_with_id
    sql: SELECT * FROM public.credential WHERE id = %s
  ###################################### 
  - name: Competency
    sql: SELECT * FROM competency ORDER BY id LIMIT $limit OFFSET $offset
  - name: Competency_with_id
    sql: SELECT * FROM public.competency WHERE id = %s
  ######################################  
  - name: Program
    sql: SELECT * FROM program p JOIN programLearningExperience ple ON p.programLearningExperienceId = ple.identifier ORDER BY programId LIMIT $limit OFFSET $offset
  - name: Program_with_id
    sql: SELECT * FROM program p JOIN programLearningExperience ple ON p.programLearningExperienceId = ple.identifier WHERE programId = %s
  ######################################  
  - name: Custom_endpoint_1
    sql: SELECT * FROM public.course
  - name: Custom_endpoint_2
    sql: SELECT p.*,c.name as course_name,c.name as competency_name, c.code as competency_code FROM person p JOIN competency c ON p.id = c.personId where p.id = %s and c.id = %s
    parameter_order: personId, competencyId
  #######################################
  - name: All_info_1
    sql: SELECT p.id,p.firstName, p.lastName,p.email, c.name as course_name, c.description as course_description, cl.type as course_learning_experience_type
      FROM person p 
      LEFT JOIN courseLearningExperience cl  ON p.id = cl.personId 
      LEFT JOIN courseAndLearningExperienceAssociation clea ON clea.courseLearningExperienceId = cl.identifier 
      LEFT JOIN course c ON c.courseId = clea.courseId
      where p.id = %s
  - name: All_info_2
    sqls: 
      - entity: Person
        sql: SELECT p.*,cl.type as course_learning_experience_type
          FROM person p 
          LEFT JOIN courseLearningExperience cl  ON p.id = cl.personId 
          where p.id = %s and cl.identifier = %s
        parameter_order: personId, courseLearningExperienceId
      - entity: Course
        sql: SELECT * FROM courseAndLearningExperienceAssociation clea
          LEFT JOIN course c ON c.courseId = clea.courseId
          WHERE courseLearningExperienceId = %s
        parameter_order: courseLearningExperienceId
  #######################################
  - name: GraphQL_Person
    sql: SELECT id, firstName, lastName, email, birthDate FROM person WHERE TRUE
    filters:
        personFirstName: 
          column: firstName
          filter_type: '='
          condition: AND
        personLastName: 
          column: lastName
          filter_type: LIKE
          condition: AND
        personEmail: 
          column: email
          filter_type: IN
          condition: OR
  - name: GraphQL_Course
    sql: SELECT p.id,p.firstName, p.lastName,p.email,c.name as course_name,c.description as course_description FROM course c JOIN courseAndLearningExperienceAssociation clea ON c.courseId = clea.courseId JOIN courseLearningExperience cl on clea.courseLearningExperienceId = cl.identifier JOIN person p ON p.id = cl.personId WHERE TRUE
    filters:
        courseName: 
          column: name
          filter_type: '='
          condition: AND
######------------ ---------------- ----------------- --------------- ------------------- --------------- --------------- 
MYSQL:
  - name: health-check
    sql: SELECT VERSION()
  - name: Person
    sql: SELECT * FROM person ORDER BY id LIMIT $limit OFFSET $offset
  - name: Person_with_id
    sql: |
      SELECT 
      p.*,
      GROUP_CONCAT(DISTINCT cle.identifier, ',') AS courseLearningExperienceIds,
      GROUP_CONCAT(DISTINCT c.courseId, ',') AS courseIds,
      GROUP_CONCAT(DISTINCT ple.identifier, ',') AS programLearningExperienceIds,
      GROUP_CONCAT(DISTINCT pr.programId, ',') AS programIds,
      GROUP_CONCAT(DISTINCT ca.id, ',') AS credentialAwardIds,
      GROUP_CONCAT(DISTINCT cr.id, ',') AS credentialIds,
      GROUP_CONCAT(DISTINCT cm.id, ',') AS competencyIds
      FROM 
      person p
      LEFT JOIN 
      courseLearningExperience cle ON p.id = cle.personId
      LEFT JOIN 
      courseAndLearningExperienceAssociation cla ON cla.courseLearningExperienceId = cle.identifier
      LEFT JOIN course c ON c.courseId = cla.courseId  
      LEFT JOIN 
      programLearningExperience ple ON p.id = ple.personId
      LEFT JOIN 
      program pr ON pr.programLearningExperienceId = ple.identifier
      LEFT JOIN 
      credentialAward ca ON p.id = ca.credentialAwardee
      LEFT JOIN 
      credential cr ON cr.credentialAwardId = ca.id
      LEFT JOIN 
      competency cm ON p.id = cm.personId
      where p.id = %s
      GROUP BY 
      p.id, p.firstName, p.lastName, p.birthDate, p.email
  - name: Person_for_Course_name
    sql: SELECT p.id,p.firstName, p.lastName,p.email,c.name as course_name,c.description as course_description FROM course c JOIN courseAndLearningExperienceAssociation clea ON c.courseId = clea.courseId JOIN courseLearningExperience cl on clea.courseLearningExperienceId = cl.identifier JOIN person p ON p.id = cl.personId WHERE c.name = %s
  - name: Person_for_Competency_name
    sql: SELECT p.id, p.firstName, p.lastName, p.birthDate, p.email FROM person p JOIN competency c ON p.id = c.personId WHERE c.name = %s
  - name: Person_for_Course_Competency_name
    sql: SELECT p.id,p.firstName, p.lastName,p.email,c.name as course_name,
      c.description as course_description , cm.name as competency_name, cm.code as competency_code
      FROM person p JOIN courseLearningExperience cl  ON p.id = cl.personId JOIN courseAndLearningExperienceAssociation clea ON clea.courseLearningExperienceId = cl.identifier JOIN course c ON c.courseId = clea.courseId
      JOIN competency cm ON p.id = cm.personId
      WHERE c.name = %s and cm.name = %s
    parameter_order: course_name, competency_name
  ###################################### 
  - name: Course
    sql: SELECT * FROM course ORDER BY courseId LIMIT $limit OFFSET $offset
  - name: Course_with_id
    sql: SELECT * FROM course WHERE courseId = %s
  ######################################
  - name: Credential
    sql: SELECT * FROM credential ORDER BY id LIMIT $limit OFFSET $offset
  - name: Credential_with_id
    sql: SELECT * FROM credential WHERE id = %s
  ###################################### 
  - name: Competency
    sql: SELECT * FROM competency ORDER BY id LIMIT $limit OFFSET $offset
  - name: Competency_with_id
    sql: SELECT * FROM competency WHERE id = %s
  ######################################  
  - name: Program
    sql: SELECT * FROM program p JOIN programLearningExperience ple ON p.programLearningExperienceId = ple.identifier ORDER BY programId LIMIT $limit OFFSET $offset
  - name: Program_with_id
    sql: SELECT * FROM program p JOIN programLearningExperience ple ON p.programLearningExperienceId = ple.identifier WHERE programId = %s
  ######################################  
  - name: Custom_endpoint_1
    sql: SELECT * FROM course
  - name: Custom_endpoint_2
    sql: SELECT p.*,c.name as course_name,c.name as competency_name, c.code as competency_code FROM person p JOIN competency c ON p.id = c.personId where p.id = %s and c.id = %s
    parameter_order: personId, competencyId
  ######################################
  - name: All_info_1
    sql: SELECT p.id,p.firstName, p.lastName,p.email, c.name as course_name, c.description as course_description, cl.type as course_learning_experience_type
      FROM person p 
      LEFT JOIN courseLearningExperience cl  ON p.id = cl.personId 
      LEFT JOIN courseAndLearningExperienceAssociation clea ON clea.courseLearningExperienceId = cl.identifier 
      LEFT JOIN course c ON c.courseId = clea.courseId
      where p.id = %s
  - name: All_info_2
    sqls: 
      - entity: Person
        sql: SELECT p.*,cl.type as course_learning_experience_type
          FROM person p 
          LEFT JOIN courseLearningExperience cl  ON p.id = cl.personId 
          where p.id = %s and cl.identifier = %s
        parameter_order: personId, courseLearningExperienceId
      - entity: Course
        sql: SELECT * FROM courseAndLearningExperienceAssociation clea
          LEFT JOIN course c ON c.courseId = clea.courseId
          WHERE courseLearningExperienceId = %s
        parameter_order: courseLearningExperienceId