name: Deploy LIF Query Cache API to Amazon ECS

env:
  AWS_REGION: us-east-1
  GHA_ROLE: "arn:aws:iam::381492161417:role/lif-github-actions-dev"
  ECS_CLUSTER: dev
  ECS_SERVICE_ORG1: query-cache-org1-FARGATE
  ECS_SERVICE_ORG2: query-cache-org2-FARGATE
  ECS_SERVICE_ORG3: query-cache-org3-FARGATE

permissions:
      id-token: write
      contents: read

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/lif_query_cache_api.yml
      - bases/lif/query_cache_restapi/**
      - cloudformation/dev-lif-query-cache.params
      - cloudformation/lif-query-cache-taskdef-includes.yml
      - components/lif/query_cache_service/**
      - components/lif/datatypes/**
      - components/lif/logging/**
      - components/lif/mongodb_connection/**
      - components/lif/exceptions/**
      - projects/lif_query_cache_api/**

jobs:

  lif-query-cache-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      WORKING_DIR: ./projects/lif_query_cache_api
      ECR_REPOSITORY: lif/dev/lif_query_cache_api
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build the project
      shell: bash
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        curl -LsSf https://astral.sh/uv/0.7.15/install.sh | sh
        ./build.sh

    - name: Build and push docker image
      uses: ./.github/actions/build-and-push
      with:
        working-dir: ${{ env.WORKING_DIR }}
        github-actions-role: ${{ env.GHA_ROLE }}
        role-session-name: query-cache-api-build
        aws-region: ${{ env.AWS_REGION }}
        ecr-repository: ${{ env.ECR_REPOSITORY }}

    - name: Update the query-cache-org1 ECS Service
      uses: ./.github/actions/update-cluster
      with:
        github-actions-role: ${{ env.GHA_ROLE }}
        role-session-name: query-cache-org1-ecs
        aws-region: ${{ env.AWS_REGION }}
        ecs-cluster: ${{ env.ECS_CLUSTER }}
        ecs-service: ${{ env.ECS_SERVICE_ORG1 }}

    - name: Update the query-cache-org2 ECS Service
      uses: ./.github/actions/update-cluster
      with:
        github-actions-role: ${{ env.GHA_ROLE }}
        role-session-name: query-cache-org2-ecs
        aws-region: ${{ env.AWS_REGION }}
        ecs-cluster: ${{ env.ECS_CLUSTER }}
        ecs-service: ${{ env.ECS_SERVICE_ORG2 }}

    - name: Update the query-cache-org3 ECS Service
      uses: ./.github/actions/update-cluster
      with:
        github-actions-role: ${{ env.GHA_ROLE }}
        role-session-name: query-cache-org3-ecs
        aws-region: ${{ env.AWS_REGION }}
        ecs-cluster: ${{ env.ECS_CLUSTER }}
        ecs-service: ${{ env.ECS_SERVICE_ORG3 }}

