name: Deploy LIF GraphQL API to Amazon ECS

env:
  AWS_REGION: us-east-1
  GHA_ROLE: "arn:aws:iam::381492161417:role/lif-github-actions-dev"
  ECS_CLUSTER: dev
  ECS_SERVICE_ORG1: graphql-org1-FARGATE
  ECS_SERVICE_ORG2: graphql-org2-FARGATE
  ECS_SERVICE_ORG3: graphql-org3-FARGATE

permissions:
      id-token: write
      contents: read

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/lif_graphql_api.yml
      - bases/lif/api_graphql/**
      - cloudformation/dev-lif-graphql.params
      - cloudformation/lif-graphql-taskdef-includes.yml
      - components/lif/mdr_client/**
      - components/lif/openapi_to_graphql/**
      - components/lif/string_utils/**
      - components/lif/logging/**
      - projects/lif_graphql_api/**


jobs:

  lif-graphql-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      WORKING_DIR: ./projects/lif_graphql_api
      ECR_REPOSITORY: lif/dev/lif_graphql_api
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build the project
      shell: bash
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        curl -LsSf https://astral.sh/uv/0.7.15/install.sh | sh
        ./build.sh

    - name: Build and push docker image
      uses: ./.github/actions/build-and-push
      with:
        working-dir: ${{ env.WORKING_DIR }}
        github-actions-role: ${{ env.GHA_ROLE }}
        role-session-name: graphql-api-build
        aws-region: ${{ env.AWS_REGION }}
        ecr-repository: ${{ env.ECR_REPOSITORY }}

    - name: Update the graphql-org1 ECS Service
      uses: ./.github/actions/update-cluster
      with:
        github-actions-role: ${{ env.GHA_ROLE }}
        role-session-name: graphql-org1-ecs
        aws-region: ${{ env.AWS_REGION }}
        ecs-cluster: ${{ env.ECS_CLUSTER }}
        ecs-service: ${{ env.ECS_SERVICE_ORG1 }}

    - name: Update the graphql-org2 ECS Service
      uses: ./.github/actions/update-cluster
      with:
        github-actions-role: ${{ env.GHA_ROLE }}
        role-session-name: graphql-org2-ecs
        aws-region: ${{ env.AWS_REGION }}
        ecs-cluster: ${{ env.ECS_CLUSTER }}
        ecs-service: ${{ env.ECS_SERVICE_ORG2 }}

    - name: Update the graphql-org3 ECS Service
      uses: ./.github/actions/update-cluster
      with:
        github-actions-role: ${{ env.GHA_ROLE }}
        role-session-name: graphql-org3-ecs
        aws-region: ${{ env.AWS_REGION }}
        ecs-cluster: ${{ env.ECS_CLUSTER }}
        ecs-service: ${{ env.ECS_SERVICE_ORG3 }}

