name: Deploy LIF Translator API to Amazon ECS

env:
  AWS_REGION: us-east-1
  GHA_ROLE: "arn:aws:iam::381492161417:role/lif-github-actions-dev"
  ECS_CLUSTER: dev
  ECS_SERVICE_ORG1: translator-org1-FARGATE
  # ECS_SERVICE_ORG1: translator-org2-FARGATE
  # ECS_SERVICE_ORG1: translator-org3-FARGATE

permissions:
      id-token: write
      contents: read

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/lif_translator_api.yml
      - bases/lif/translator_restapi/**
      - cloudformation/dev-lif-translator-org1.params
      # - cloudformation/dev-lif-translator-org2.params
      # - cloudformation/dev-lif-translator-org3.params
      - cloudformation/lif-translator-taskdef-includes.yml
      - components/lif/exceptions/**
      - components/lif/logging/**
      - components/lif/mdr_client/**
      - components/lif/translator/**
      - projects/lif_translator_api/**

jobs:

  lif-translator-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      WORKING_DIR: ./projects/lif_translator_api
      ECR_REPOSITORY: lif/dev/lif_translator_api
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build the project
      shell: bash
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        curl -LsSf https://astral.sh/uv/0.7.15/install.sh | sh
        ./build.sh

    - name: Build and push docker image
      uses: ./.github/actions/build-and-push
      with:
        working-dir: ${{ env.WORKING_DIR }}
        github-actions-role: ${{ env.GHA_ROLE }}
        role-session-name: translator-api-build
        aws-region: ${{ env.AWS_REGION }}
        ecr-repository: ${{ env.ECR_REPOSITORY }}

    - name: Update the lif-translator-org1 ECS Service
      uses: ./.github/actions/update-cluster
      with:
        github-actions-role: ${{ env.GHA_ROLE }}
        role-session-name: translator-org1-ecs
        aws-region: ${{ env.AWS_REGION }}
        ecs-cluster: ${{ env.ECS_CLUSTER }}
        ecs-service: ${{ env.ECS_SERVICE_ORG1 }}
#
#     - name: Update the lif-translator-org2 ECS Service
#       uses: ./.github/actions/update-cluster
#       with:
#         github-actions-role: ${{ env.GHA_ROLE }}
#         role-session-name: translator-org2-ecs
#         aws-region: ${{ env.AWS_REGION }}
#         ecs-cluster: ${{ env.ECS_CLUSTER }}
#         ecs-service: ${{ env.ECS_SERVICE_ORG2 }}
#
#     - name: Update the lif-translator-org3 ECS Service
#       uses: ./.github/actions/update-cluster
#       with:
#         github-actions-role: ${{ env.GHA_ROLE }}
#         role-session-name: translator-org3-ecs
#         aws-region: ${{ env.AWS_REGION }}
#         ecs-cluster: ${{ env.ECS_CLUSTER }}
#         ecs-service: ${{ env.ECS_SERVICE_ORG3 }}

